### PR TITLE
Fixes for host resolution on windows and synchronous server calls

### PR DESCRIPTION
**Pull request by kkretzschmar**
Hi Juan,
I fixed the windows issues and windows is fine now. My fixes in baseclient wont win a C++ award, but we already agreed that we have to reimplement the client part. 

I had to revert your latest change wrt "waiting that the server has finished the new property" requests. This change actually broke the javascript execution which sends in general synchronous events. 

When the client sends a new property to the server, it internally sets the server side instance of that property to state=busy _before_ sending the command to the server.  The properties in the PI process instance propertyList are different objects, they reflecting the value _after_  receiving property updates in the server. So this list is a mirror of the actual current property values in the server. 

In general, Javascript execution of the INDI modules has completely different synchronicity requirements than execution with the interface (humans are slow). I created these javascript unit tests in order to check automatically that the javascript integration works. If we run that tests we are sure that our changes did not change these synchronicity requirement which are normally not tested when testing the functionality manually.

Is there a way to integrate the Javascript unit tests in the PI platform only for DEV machines, so that these tests do not reach the users? I am planning to write more automatic unit tests for the other modules.

Seems that we are now _ready_ for release! Juan, thank you so much for helping me to stabilize the modules and making the GUIs looking better. And big thanks to Vicent for the improvement suggestions, I like the new AutoStretch and viewing in-place functionality!!  

Klaus

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Klaus,

> When the client sends a new property to the server, it internally sets the server side instance of that property to state=busy before sending the command to the server. The properties in the PI process instance propertyList are different objects, they reflecting the value after receiving property updates in the server. So this list is a mirror of the actual current property values in the server. 

The problem is that this code that you have reverted crashes the whole PixInsight Core application on OS X, in particular when using the INDI Server application by CloudMakers (http://www.cloudmakers.eu/indiserver/), which is the solution I have tested (and, IMO, the *only* reasonable solution on OS X from a normal user's perspective). That's why I wrote a different way to implement synchronous server calls, which works on Linux, FreeBSD and OS X (I haven't tested it on Windows, but it should work also). My solution is a simple loop that keeps watching the INDI server until the property that has been changed is no longer busy, that is, until it is in an OK, IDLE, or ALERT state (throwing an appropriate exception in the latter case), or until the user aborts execution.

I don't understand why this causes problems with your JavaScript test units, but tomorrow I'll investigate it. This is a serious problem that we have to solve before releasing the module, since it breaks it completely on OS X.

Another problem is when a synchronous call takes some time to complete (for example, in a real situation with the server running remotely and communicating through a network connection, which can be slow or have issues). In these cases it is mandatory to invoke Module->ProcessEvents() periodically, or the whole platform freezes. Note also that without calling this routine, the user has no way to cancel or abort an ongoing operation.

> Is there a way to integrate the Javascript unit tests in the PI platform only for DEV machines, so that these tests do not reach the users? I am planning to write more automatic unit tests for the other modules.

We can distribute them through the update-devel repository, which is not enabled by default.

Other than this showstopper problem, it seems we have it ready now. Thank you for fixing the Windows issues! And a huge THANK YOU for creating this module and taking this initiative.

**Comment by jconejero** [comment]
By the way, I haven't merged your pull request because I have to understand/fix the issue on OS X first. I'll start to work on this tomorrow.

**Comment by kkretzschmar** [comment]
Hi Juan,
>The problem is that this code that you have reverted crashes the whole
>PixInsight Core application on OS X,

Ah Ok, I wasn't aware of this. This part of the Device Controller code is
quite old and afaik it worked on OSX in the early stage of the prototype.
But I never tested it with the CloudMakers INDI server. I used an INDI
server on Linux remotely.

>My solution is a simple loop that keeps watching the INDI server until the
>property that has been changed is no longer busy, that is, until it is

Yes, the point is that the states have to be set to "busy" before sending
the command to the server and that is not the case for the property states
in the property table, because these states reflect the properties of the
server. I tried to fix that but then I went into an endless loop within the
waiting monitor ...

>In these cases it is mandatory to invoke Module->ProcessEvents()
>periodically,
I agree.

>We can distribute them through the update-devel repository, which is not
>enabled by default.
Cool, great!


Klaus

2016-05-01 22:27 GMT+02:00 Juan Conejero <notifications@github.com>:

**Comment by jconejero** [comment]
Hi Klaus,

See my latest update with version 1.0.9. The previous version is on the INDIClient.old folder for reference. The new version includes your fixes on Windows (the func/FUNCTION issue is now fixed in pcl/Defs.h with a new PCL_FUNCTION_NAME macro) and has no problems with synchronous property updates, so I'm closing this pull request.

I have modified/rewritten a significant amount of code, basically to implement a new thread-safe server synchronization mechanism (new exclusive access device and property lists, fully based on PCL code), to remove all dependencies on process instances belonging to interfaces, and to clean/prepare everything for the intense development we're going to do during the next months.

INDIDeviceControllerInstance and INDIClient are now completely independent. These classes have no friend classes now, with the obvious exception of INDIDeviceControllerInterface, which is a friend of INDIDeviceControllerInstance in order to generate new instances (customary in PCL). INDIClient implements now a "reported changes" paradigm to provide real-time, accurate information about new/removed devices and new/removed/updated properties in a thread-safe way. This allows for efficient real-time GUI updates in INDIDeviceControllerInterface, as well as other real-time interfaces that we may implement in the future.

INDIDeviceControllerInterface has now a single TreeBox with all devices and their properties, and a single button to connect/disconnect devices and edit properties. This button (GUI->NodeAction_PushButton) changes dynamically as a function of the current tree item. You can also perform these actions by activating a tree item (double click or press Enter).

Of course, I realize there are many more structural changes that must be described and justified. I'll do that tomorrow.

I have revised also your JavaScript test suite, which you'll find on the INDIClient/tests subdirectory. Now it uses a new Test PJSR object, based on your original code (great contribution BTW). The new version of the INDIClient module passes all 10 tests consistently. 

As soon as you review it and give me your permission, this version is now ready for immediate release. It still should be tested on Windows, but there should be no problems. Can you test it?

I hope you like and agree with all changes I've made. Let me know if there are problems, or if you don't agree with anything.

**Comment by kkretzschmar** [comment]
Hi Juan,
wow first glimpse on the code looks very good, compact and easy to
understand. The issue you have observed was an thread issue I guess. I
remember that I missed to build an exclusive access for the device list ...

I also agree that the visitor pattern for the GUI tree boxes are a bit
exaggerated, the tree will never have a depth > 3 ...

I'll test on windows asap...

I'm happy that you like my proposal for a Java test framework. The
javascript integration is ideal for these kind of automatic testing.

Thanks!
Klaus

Am Sonntag, 8. Mai 2016 schrieb Juan Conejero :

**Pull request closed without merging**
