### PR TITLE
Removing DevTools

### PR DESCRIPTION
**Pull request by GeorgViehoever**
because they appear to be not used and maintained. If you like, you can still find "my" version of these in repository GeorgViehoever/GvPiDevTools

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Georg,

Sorry for the delay... I've been pretty busy lately. How about integrating your [GvPiDevTools](https://github.com/GeorgViehoever/GvPiDevTools) with the official PCL distribution? They are very nice and can help other people to improve their work on PCL development.

**Comment by jconejero** [comment]
By the way, if you decide to integrate your GvPiDevTools, they should be under the new [src/utils](https://github.com/PixInsight/PCL/tree/master/src/utils) directory.

**Comment by GeorgViehoever** [comment]
No problem with the delay. 
The tools you just removed from the distribution are the precursors of the GviDevTools. They were totally out of date, and nobody complained. So I felt that it was probably better to just keep the variant that is useful for me, instead of trying to develop them into some generally useful toolset.
I would happily contribute them to PCL if somebody takes care of them. And maybe you could also add some of the utilities that you surely have ?!?
Best,
Georg

Georg Viehöver (georg.viehoever@web.de)

**Comment by jconejero** [comment]
I look forward to your pull request. Yes, I do have many utilities, including code maintenance applications, testing applications and scripts, and proofs of concept scripts. Some of them may be of public interest. As soon as I have some time, I'll commit them here.

**Pull request merged**
