### PR TITLE
CometAligment History KeyWords added

### PR DESCRIPTION
**Pull request by nik-volkov**

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Nikolay. Welcome to GitHub! I am glad to have you contributing here ;)

Thank you for this pull request. Just a small problem:

#define MODULE_VERSION_BUILD 0001

Please don't reset build numbers. Build version numbers must always be increasing because they play the role of uniquely identifying software releases. In this case MODULE_VERSION_BUILD should be greater than 65, which is the build number of the latest public release.

Normally each developer or development team has his or her own rules to assign build numbers. Some people count the number of compilations automatically. Personally I prefer to increase builds in a more subjective (and slower) way. My "build number unit" is related to relevant changes in the code, not necessarily corresponding to actual compilation builds. I recommend you follow a similar rule, where MODULE_VERSION_BUILD grows faster than MODULE_VERSION_REVISION to give an idea of the relative "amount of change" in each version.

As soon as you fix this issue I'll merge your pull requests.

By the way, I'm going to invite you to join our official team of contributors as soon as I send this comment.

**Comment by nik-volkov** [comment]
CometAligment MODULE_VERSION_BUILD 0066
Done.

**Comment by jconejero** [comment]
Hi Nikolay,

I see that you have closed this pull request. Has this been intentional? Do you want me to reopen and merge it now?

**Comment by nik-volkov** [comment]
Hi, Juan.
Yes, please merge it now.

**Pull request merged**
