### PR TITLE
New module: INDIMount

### PR DESCRIPTION
**Pull request by kkretzschmar**
Hi Juan,
I found time to work on the INDI Mount module. I was able to fix the compile errors and some bugs inside the module. I also found that I could reuse some methods of your Stargenerator module (Stardatabase, Projections,etc). Would it be possible to move these classes to the PCL library to reuse them in other modules?

Thanks,
Klaus

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Klaus,

Great! Yes, it should be possible to include StarGenerator code in the PCL distribution without problems. I'll try to get this work done as soon as possible.

Unfortunately, I've had no time to complete the necessary work on the rest of your INDI modules. The maximum priority is now releasing an official 1.8.4 version of PixInsight on all platforms, especially on OS X. This is becoming a big nightmare, mainly because of numerous Qt bugs on this platform, but I am very close now.

How about releasing your modules as an official update? Do you think this is doable---not for the next 1.8.4 release, but as an update before the end of the year for example. Which work needs to be done/completed to achieve this goal?

Nice work as always!

**Comment by kkretzschmar** [comment]
Hi Juan,
>Yes, it should be possible to include StarGenerator code in the PCL distribution without problems.  >try to get this work done as soon as possible.

Great! I am also thinking about to use the information of the telescope coordinates to do a plate solving of the frames aquired by the CCDFrame module. This can be used to center objects, or run an automated aligment algorithm for the telescope mount (which already exists in the INDI device implementations for some telescopes). This would require to call the image staraligment functions from the core platform from a C++ module. Is this possible ?

>Unfortunately, I've had no time to complete the necessary work on the rest of your INDI modules. 

No problem, the remaining work was negligible and I learned more about the changes you made in the string classes.    

>The maximum priority is now releasing an official 1.8.4 version of PixInsight on all platforms, >especially on OS X. This is becoming a big nightmare, mainly because of numerous Qt bugs on >this platform, but I am very close now.

Yes, I read about these problems in the forum... Good luck to you that you have fixed them now.

>How about releasing your modules as an official update? Do you think this is doable---not for the >next 1.8.4 release, but as an update before the end of the year for example. Which work needs to >be done/completed to achieve this goal?

By the end of the year could be a challenge, but I think to start with it would make sense to release the Client + CCDFrame modules only. And if that works, the INDI Mount module later.

The work which have to be completed is:
- Bug fixes
  Seems that I have non-exclusive accesses to some shared data, which sporadically appears when  the network connection is bad. Additionally sporadically there seems to be  a problem finding  the /tmp folder, especially after initially starting the module
- Type specific input controls for the Client Module as well (e.g. numeric controls, etc)
- Docu -> no docu at all right now :-(
- Testing ...

So a lot of things have to be done, but it is doable. I have used my modules last week to aquire lots of frames of the little Dumbell Nebula, the Bubble Nebula, and Comet Panstarrs and it worked fine..,

Best regards,
Klaus

**Comment by kkretzschmar** [comment]
Hi Juan,
I have a release candidate now (not pushed to github now). However, while
testing I get a Signal 11 from a allocation method within the string class
(crash dump below).

The crash appears when a timer event (__UpdatePropertyList_Timer) is
triggered by another timer event (__UpdatePropertyList_Timer) which itself
is maybe not so optimal.  The crash happens in

pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Data::NextFree()


in line


freeList = reinterpret_cast<Data*>( data->string );


not sure what the problem could be here. Do you have an idea?


Thanks,
Klaus



Critical signal caught (11): Segmentation violation



PixInsight 01.08.04.1195 - Critical Signal Backtrace

Signal : 11

Module : /opt/PixInsight/bin/PixInsight() [0x14096ad]

========================================================================================================================

59: /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f1505e05340]

58: pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Data::NextFree()(+0x3e [0x7f146cf14265])

57: pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Data::New(unsigned long)(+0x14 [0x7f146cf140ef])

56: pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::UninitializedGrow(unsigned long&, unsigned
long)(+0x1f7 [0x7f146cf20167])

55: void pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Insert<pcl::CharTraits,
pcl::StandardAllocator>(unsigned long, pcl::GenericString<unsigned short,
pcl::CharTraits, pcl::StandardAllocator> const&)(+0x42 [0x7f146cf1ff3e])

54: void pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Append<pcl::CharTraits,
pcl::StandardAllocator>(pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator> const&)(+0x27 [0x7f146cf20239])

53: pcl::String::Append(pcl::String const&)(+0x23 [0x7f146cf1d92b])

52: pcl::operator+(pcl::String&&, pcl::GenericString<unsigned short,
pcl::CharTraits, pcl::StandardAllocator> const&)(+0x3b [0x7f146cf27d94])

51: pcl::PropertyUtils::getKey(pcl::String, pcl::String, pcl::String)(+0x94
[0x7f146cf39a22])

50: pcl::PropertyTree::addElementNode(pcl::String, pcl::String,
pcl::String, int, pcl::String)(+0x5a8 [0x7f146cf528dc])

49: pcl::INDIDeviceControllerInterface::UpdatePropertyList()(+0x693
[0x7f146cf37a05])

48:
pcl::INDIDeviceControllerInterface::__UpdatePropertyList_Timer(pcl::Timer&)(+0x3e
[0x7f146cf346b0])

47: pcl::TimerEventDispatcher::TimerNotify(void*, void*)(+0x93
[0x7f146d012afb])

46: QObject::event(QEvent*)(+0x6c [0x7f1500b9f79c])

45: QApplicationPrivate::notify_helper(QObject*, QEvent*)(+0x8c
[0x7f150173c7fc])

44: QApplication::notify(QObject*, QEvent*)(+0x3b8 [0x7f1501741718])

43: /opt/PixInsight/bin/PixInsight() [0x5d26ff]

42: QCoreApplication::notifyInternal(QObject*, QEvent*)(+0x65
[0x7f1500b6eed5])

41: QTimerInfoList::activateTimers()(+0x55d [0x7f1500bc4fdd])

40: /opt/PixInsight/bin/lib/libQt5Core.so.5(+0x2ed401) [0x7f1500bc5401]

39: /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)
[0x7f150605be04](+0x254 [0x7f150605be04])

38: /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048) [0x7f150605c048]

37: /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)
[0x7f150605c0ec](+0x2c [0x7f150605c0ec])

36:
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)(+0x5c
[0x7f1500bc56cc])

35: /opt/PixInsight/bin/PixInsight() [0x4c0bc0]

34: pcl::Control::EnableUpdates(bool)(+0x39 [0x7f146cf726cb])

33: pcl::Control::DisableUpdates(bool)(+0x29 [0x7f146cf38e1d])

32: pcl::INDIDeviceControllerInterface::UpdateDeviceList()(+0x33
[0x7f146cf31f75])

31:
pcl::INDIDeviceControllerInterface::__UpdateDeviceList_Timer(pcl::Timer&)(+0x3d
[0x7f146cf3466f])

30: pcl::TimerEventDispatcher::TimerNotify(void*, void*)(+0x93
[0x7f146d012afb])

29: QObject::event(QEvent*)(+0x6c [0x7f1500b9f79c])

28: QApplicationPrivate::notify_helper(QObject*, QEvent*)(+0x8c
[0x7f150173c7fc])

27: QApplication::notify(QObject*, QEvent*)(+0x3b8 [0x7f1501741718])

26: /opt/PixInsight/bin/PixInsight() [0x5d26ff]

25: QCoreApplication::notifyInternal(QObject*, QEvent*)(+0x65
[0x7f1500b6eed5])

24: QTimerInfoList::activateTimers()(+0x55d [0x7f1500bc4fdd])

23: /opt/PixInsight/bin/lib/libQt5Core.so.5(+0x2ed401) [0x7f1500bc5401]

22: /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x254)
[0x7f150605be04](+0x254 [0x7f150605be04])

21: /lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x49048) [0x7f150605c048]

20: /lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)
[0x7f150605c0ec](+0x2c [0x7f150605c0ec])

19:
QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)(+0x5c
[0x7f1500bc56cc])

18: /opt/PixInsight/bin/PixInsight() [0x502b1b]

17: pcl::MetaModule::ProcessEvents(bool)(+0x52 [0x7f146cf980b6])

16: pcl::ProcessInterface::ProcessEvents(bool)(+0x32 [0x7f146cfb153a])

15: pcl::CCDFrameInterface::StartExposureButton_Click(pcl::Button&,
bool)(+0x513 [0x7f146cf1cc3b])

14: pcl::ButtonEventDispatcher::Click(void*, void*, unsigned int)(+0x9e
[0x7f146cf6a13b])

13: QMetaObject::activate(QObject*, int, int, void**)(+0x7e6
[0x7f1500b9eba6])

12: QAbstractButton::clicked(bool)(+0x32 [0x7f1501abf762])

11: /opt/PixInsight/bin/lib/libQt5Widgets.so.5(+0x2692b6) [0x7f15018352b6]

10: /opt/PixInsight/bin/lib/libQt5Widgets.so.5(+0x269eee) [0x7f1501835eee]

9: QAbstractButton::mouseReleaseEvent(QMouseEvent*)(+0xd4 [0x7f1501836064])

8: /opt/PixInsight/bin/PixInsight() [0x1211fa3]

7: QWidget::event(QEvent*)(+0x831 [0x7f150177c9a1])

6: QApplicationPrivate::notify_helper(QObject*, QEvent*)(+0x8c
[0x7f150173c7fc])

5: QApplication::notify(QObject*, QEvent*)(+0x9bb [0x7f1501741d1b])

4: /opt/PixInsight/bin/PixInsight() [0x5d26ff]

3: QCoreApplication::notifyInternal(QObject*, QEvent*)(+0x65
[0x7f1500b6eed5])

2: QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*,
QWidget*, QWidget**, QPointer<QWidget>&, bool)(+0x391 [0x7f1501740be1])

1: /opt/PixInsight/bin/lib/libQt5Widgets.so.5(+0x1c957b) [0x7f150179557b]

========================================================================================================================




2015-11-19 11:32 GMT+01:00 Juan Conejero <notifications@github.com>:

**Comment by kkretzschmar** [comment]
some additonal info from gdb

$1 = (pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Data *) 0x3600340020006b
(gdb) list
4562          {
4563             if ( freeLock.TestAndSet( 0, 1 ) )
4564             {
4565                Data* data = freeList;
4566                if ( data != nullptr ){
4567                   freeList = reinterpret_cast<Data*>( data->string );
4568                }
4569                freeLock.Store( 0 );
4570                return data;
4571             }
(gdb) print freelist
$2 = (struct requestlist *) 0x0
(gdb) print freeLock
$3 = {m_value = 1}
(gdb) print data
$4 = (pcl::GenericString<unsigned short, pcl::CharTraits,
pcl::StandardAllocator>::Data *) 0x3600340020006b
(gdb)

Seems that NextFree is not thread safe ...

Klaus

2016-01-06 22:28 GMT+01:00 Klaus Kretzschmar <kkretzschmar@googlemail.com>:

**Comment by jconejero** [comment]
Hi Klaus,

The free list allocation algorithm implementation of GenericString<>, 
including of course String::Data::FreeList(), is thread-safe.

I have attached a modified version of SandboxInstance.cpp that 
demonstrates this. See the relevant code from lines 107 to 164. Simply 
replace SandboxInstance.cpp with this modified version, build the 
Sandbox module, and replace bin/Sandbox-pxm.so in your distribution. Run 
PixInsight, open any image, and execute the Sandbox process several 
times. In my workstation with 24 cores this modified version generates 
240000 random strings with 24 threads. The result is written to 
/tmp/test.txt. The code runs without any problems.

So the problem must be anywhere else, including the possibility of a 
free list corruption, but the cause is not a thread safety bug in 
String. I'd need to see your code to say anything more precise.

Looking forward to your release candidate!

Happy new year by the way!

Juan

**Comment by jconejero** [comment]
In case you receive the wrong email... I have discovered that GitHub doesn't allow attachments, so I have modified my previous answer to paste SandBoxInstance.cpp's source code at the end of the message. Sorry for the mess.

**Comment by kkretzschmar** [comment]
Hi Juan,
>Happy new year by the way!
Happy new year to you as well!

>So the problem must be anywhere else, including the possibility of a
>free list corruption, but the cause is not a thread safety bug in
>String. I'd need to see your code to say anything more precise.

Yes, you are right. I think it is an memory corruption in my software in a
code section where I am trying dirty reads on Array elements while the
Array can be changed in a separate thread. I think this wont work and I
have to introduce locks ...

Thanks !

Klaus





2016-01-11 11:15 GMT+01:00 Juan Conejero <notifications@github.com>:

**Comment by jconejero** [comment]
You can use the Mutex and AutoLock classes, along with AtomicInt, if it is suitable. Let me know if you need help with these.

**Comment by kkretzschmar** [comment]
Thanks, with Mutex and AutoLock it works now. No crashes anymore.

2016-01-11 12:00 GMT+01:00 Juan Conejero <notifications@github.com>:

**Pull request merged**
