### PR TITLE
Print latest server log entry to conole

### PR DESCRIPTION
**Pull request by kkretzschmar**
Hi Juan,
during my testing I found a problem which has its origin in a bug in the current INDI CCD driver implementation. The current INDI CCD driver accepts setting server side download directories which do not exists. This leads to an endless loop (in the Spinstatus) when using the upload mode "UploadServerAndClient". Of course, it is possible to abort the process but you don't get the info what happend, also because the INDIClient process GUI is set to disabled mode. 

I fixed this by writing the latest INDI server log entry to the console, so that the user get noticed that something went wrong. I'll also ask the INDI forum whether they could provide a directory exists on server side.   

I'd prefer if we could re-enable the interactive mode with the INDICCDFrame and INDIDeviceController default GUI before releasing our first version - especially the INDIDeviceController is a kind of Monitor which provides a lot of status information. It should not be blocked during process runtime (if not used via javascript exectuteGlobal())

I have a very simple javascript demo, which works fine. I'd like to use simple javascript unittests for testing with a local INDI server and simulator devices. Do you already have an javascript asserts module? 

I also have difficulties to find the  value of the Gobal setting "ImageWindow/DownloadsDirectory" I cannot find it in the Global Preferences process. Do I have to recompile _all_ modules, to get the new global settings?

Happy Easter
Klaus

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Klaus,

Sorry for the long delay, Some personal issues have gotten in the way and I've been offside for more time than expected. I am here again and starting to work on your module again. Let's see if we can release it about the end of this week / beginning of next one.

> I'd prefer if we could re-enable the interactive mode with the INDICCDFrame and INDIDeviceController default GUI before releasing our first version

OK. Let me think on the best way to recover this functionality by reusing instance routines (I mean, code from ExecuteGlobal() and auxiliary functions).

This can be done, of course. Anyway, you can always run a second instance of the PixInsight Core application to use a new INDIDeviceController interface while the first instance is running. This is an interesting possibility IMO.

> Do you already have an javascript asserts module?

Nope. But it seems pretty easy to write an assert() function to terminate the running script if the argument condition is false. Do you refer to that function?

> I also have difficulties to find the value of the Gobal setting "ImageWindow/DownloadsDirectory"

Use this expression from JavaScript:

`Settings.readGlobal( "ImageWindow/DownloadsDirectory", DataType_UCString )`

(you need to #include \<pjsr/DataType.jsh\>)

From C++, you should use the static function:

`String PixInsightSettings::GlobalString( const IsoString& globalId )`

so for example:

`String downloadsDir = PixInsightSettings::GlobalString( "ImageWindow/DownloadsDirectory" );`

Let me know if this helps.

**Comment by kkretzschmar** [comment]
Hi Juan,
>see if we can release it about the end of this week / beginning of next
one.
OK, cool.

>OK. Let me think on the best way to recover this functionality by reusing
instance routines (I mean, code from ExecuteGlobal() and auxiliary
functions).
Right, I agree.

>Nope. But it seems pretty easy to write an assert() function to terminate
the running script if >the argument condition is false. Do you refer to
that function?
Yes, in the meantine I wrote a simple Assert.jsh file together with a
simple javascript unit testing framework as a jsh module for automatic
testing. I'll push these files to PJSR repository soon ...

>Use this expression from JavaScript:
Thanks! In my unit tests I take the images directly from
ImageWindow.activeWindow or ImageWindow.windows, so I don't need to load
the file from filesystem anymore.


Currently I require that a INDIDeviceController instance is running before
starting  the javascript unit tests.

Some tests, like for serverUpload are only meaningful when the INDI server
runs on localhost. Is there a method to attach from javascript to a running
process, in order to read out some parameters like e.g. the serverHostname?
Or maybe I should create a INDIDeviceController instance from javascript as
well to have everything under control ...

Klaus


2016-04-05 13:16 GMT+02:00 Juan Conejero <notifications@github.com>:

**Comment by jconejero** [comment]
Hi Klaus,

The server file name template functionality is now implemented; I have just committed the changes. See INDICCDFrameInterface.cpp for template syntax and INDICCDFrameInstance for the implementation, and please feel free to add new template specifiers as you see fit for them.

Yesterday I met Vicent Peris and we made a sort of brainstorming around the INDICCDFrame process. Along with the need for an interactive acquisition mode (your original Start and Stop buttons), we figured out a few useful new features that seem pretty easy to implement:

- Allow for continuous exposures, that is, an unlimited number of exposures. For example, by setting number of frames = 0.

- When uploading acquired images to the client, implement an option to reuse the same image window, instead of creating new ones. Very useful for focusing and framing.

- Apply an automatic STF AutoStretch transformation to acquired client images.

- New parameters to restrict the acquisition window to user-specified coordinates in device pixels. Also very useful for focusing.

- A new option to save images on the client side.

I can implement all of these features easily. What do you think?

**Comment by kkretzschmar** [comment]
Hi Juan,
sounds good!

>I can implement all of these features easily.
Yes please go ahead. I am still working on a better integration of the
INDIDeviceController . It is now possible to connect  to INDI server and
INDI devices from javascript only. So my javascript unit tests run without
the necessity to start the INDIDeviceController process.



2016-04-07 16:52 GMT+02:00 Juan Conejero <notifications@github.com>:

**Comment by jconejero** [comment]
Hi Klaus,

I have just uploaded a new version with interactive image acquisition functionality implemented. See the new class AbstractINDICCDFrameExecution in INDICCDFrameInstance.h, and its implementation at the bottom of INDICCDFrameInstance.cpp.

See also the derived classes in INDICCDFrameInstance.cpp (line 300) and INDICCDFrameInterface.cpp (line 871). As you can see, AbstractINDICCDFrameExecution provides a generalized, event-driven image acquisition routine that can be specialized to implement global instance execution and interactive execution very easily. The same strategy could be used to implement INDIMountInstance and INDIMountInterface. Please let me know what do you think about this solution.

With these changes, the module is almost ready for a first "preview" relase IMO. I would release it only with INDIDeviceController and INDICCDFrame enabled, that is, without INDIMount. Let me know if you agree.

**Comment by kkretzschmar** [comment]
Hi Juan,

>I have just uploaded a new version with interactive image acquisition
functionality >implemented. See the new class AbstractINDICCDFrameExecution
in >INDICCDFrameInstance.h, and its implementation at the bottom of
>INDICCDFrameInstance.cpp.

>See also the derived classes in INDICCDFrameInstance.cpp (line 300) and
>INDICCDFrameInterface.cpp (line 871). As you can see,
>AbstractINDICCDFrameExecution provides a generalized, event-driven image
acquisition >routine that can be specialized to implement global instance
execution and interactive
Great, I'll look at it soon.

>execution very easily. The same strategy could be used to implement
INDIMountInstance >and INDIMountInterface. Please let me know what do you
think about this solution.

I didn't start with the INDIMount integration as a "globalexecutable"
process so far, so I'll implement the same pattern here as well.

>With these changes, the module is almost ready for a first "preview"
relase IMO. I would >release it only with INDIDeviceController and
INDICCDFrame enabled, that is, without >INDIMount. Let me know if you
agree.

Absolutely. Thanks for enabling the interactive mode again!



2016-04-15 18:10 GMT+02:00 Juan Conejero <notifications@github.com>:

**Pull request merged**
