### PR TITLE
External tool

### PR DESCRIPTION
**Pull request by GeorgViehoever**
Hi Juan,

today I give to you a new module that allows to better integrate PixInsight with external programs. I have been working on it for the last 3 months, after considering some comments on the forum.

I would currently consider it to have early Beta status. Before I make it known to a larger public, I would like you and the PI team to have a careful look, suggest/provide improvements, test/compile on non-Linux platforms etc..

Please let me know what you think. Below an excerpt from the documentation.

Georg

The astronomical community provides a lot of free and/or open source tools that can solve tasks difficult to solve with PixInsight alone. The ExternalTool module enables PixInsight to use many of these tools as if they were part of PixInsight. The only requirement is that they can be called via a command line, and that they can read and write FITS files. Instances of ExternalTool can be used on full images or previews, as part of process flows, applied with process containers, stored on a workspace, file or project, or used with PJSR - just as with any regular PixInsight process. For suitable external tools, even Realtime Previews can be generated. 
 
In its basic operation, ExternalTool 

* stores the target image to a file, including its FITS keywords and ICC profile, 
* calls an executable with user defined parameters, plus the filename of the input file and an output file name, 
* monitors execution, displaying any messages on the Process Console Window, and 
* on termination, it checks for the exit code and if necessary display an error message. If successful, it replaces the target image with the result image, truncating its values if necessary and transfering FITS keywords and ICC profile from the result file into PixInsight.

Compared to other solutions, such as using the  "!" Process Console command, or the PJSR ExternalProcess object, the ExternalTool process provides GUI, ease of use, and the full integration that only PCL modules can provide. 
 
The tool comes with a number of example tools, allowing to compute intensity contours, call the Aladin interactive sky atlas, plot a visibility calender of the major planets, or use the astronomy.net Blind Solver web service to platesolve images.

### CODE REVIEW

**Comment by jconejero** [comment]
Hi Georg,

This is a very interesting project. I don't see any problem to merge it right now; will let you know when I have tested it.

Thank you so much!

**Comment by GeorgViehoever** [comment]
Hi Juan,
any progress with looking at this? What is the plan?
Georg

**Comment by jconejero** [comment]
Hi Georg,
Sorry not to reply sooner! As I have said in my answer to Klaus, I am extremely busy with the next versions of PCL and PI Core. Please bear with me for a few days while I stabilize everything a little (e.g., right now the PI Core application does not compile :-S ). As soon as I can I'll take a deep look at your module. As in the case of Klaus' PixInsightINDIClient module, we should release your module through update-devel and send a mass email message to let everybody know about your work.

**Comment by GeorgViehoever** [comment]
No worries, Juan. Just make sure you test the basic functionality of the module on non-Linux machines before releasing it - I have no way to do this here. As usual: You are setting the priorities....

**Pull request merged**
