### PR TITLE
Fix build on windows

### PR DESCRIPTION
**Pull request by kkretzschmar**

### CODE REVIEW

**Comment by kkretzschmar** [comment]
Hi Juan,
thanks for fixing the issues in my code.

I have a strange error message which came up after I applied the last
PixInsight update (see attachment). At the same time I also updated the PCL
branch from github.

The error is a fatal error reporting "Error writing settings data (bool)"
when I exit PixInsight. Even when I do nothing with PI justing exiting,
this error message occurs and PI hangs, I have to kill the process.

When I have process open (e.g. Dynamic crop) and exit PI the I get in
addtion an API error:

"Settings: Error writing local integer data:
Interfaces/DynamicCrop/Geometry/Top"

First I thought it has to do with my client development, but even when I
disable my plugin the error occurs.

It seems to be a problem with file I/O. The problem occurs also when I try
to overwrite an existing image with "Save as"

Have you seen such a problem before?

I am using Ubuntu 14.04 with the latest PI core version. Reinstallation did
not work.

Thanks,
Klaus


P.S. I am writing this bug message here, since I am not sure whether it
belongs to my development. But I think not
...


2016-01-25 11:11 GMT+01:00 Juan Conejero <notifications@github.com>:

**Comment by jconejero** [comment]
Hi Klaus,

This problem is very strange. I have seen something similar (bool settings write error on exit) on a Windows 7 machine. However, this has never happened on the rest of our testing machines, including Linux, OS X and Windows (7, 8.1 and 10) physical and virtual machines. Indeed it looks like a file I/O problem, perhaps caused by a permissions issue in your case (typical problem on UNIX/Linux environments), or maybe a rare Qt bug.

Try resetting all application settings by launching the application as follows:

$ pixinsight --uninstall

This will remove all settings created by the core application and all scripts and modules. Let me know if this helps.

**Comment by kkretzschmar** [comment]
HI Juan,
thanks.

>PixInsight Core 01.08.04.1195 Ripley (x64)
>Copyright (c) 2003-2015 Pleiades Astrophoto

>This application failed to start because it could not find or load the Qt
platform plugin "xcb".

>Reinstalling the application may fix this problem.


There is no libqxcb.so neither in the installation directory nor in the lib
subfolder

Klaus


2016-01-26 17:06 GMT+01:00 Juan Conejero <notifications@github.com>:

**Comment by kkretzschmar** [comment]
Sorry, I found it now in lib/qt-plugins/platform

ldd on libqxcb.so shows that libQt5XcbQpa.so.5 cannot be found.


libQt5XcbQpa.so.5 => not found

2016-01-26 21:00 GMT+01:00 Klaus Kretzschmar <kkretzschmar@googlemail.com>:

**Comment by kkretzschmar** [comment]
Finally I made it with the script: PixInsight.sh --uninstall.

Yes, it solved the problem, thanks !!

2016-01-26 21:06 GMT+01:00 Klaus Kretzschmar <kkretzschmar@googlemail.com>:

**Pull request merged**
