### PR TITLE
Drizzle implemented into the second pass(operand subtraction mode) of CometAlignment

### PR DESCRIPTION
**Pull request by nik-volkov**

### CODE REVIEW

**Comment by GeorgViehoever** [comment]
Hi,
I had difficulties to compile the previously submitted version with the version of the PCL repository that I had. It appeared that a few files could not be found. Did you check that everything compiles OK with this version?
Georg

**Comment by nik-volkov** [comment]
Hi Georg.
Which files could not be found? DrizzleDataDecoder.h ?
If Yes, take it from PCL distribution package.

**Comment by GeorgViehoever** [comment]
Hi Nikolai,
I will check if I can compile later this week.
Georg

**Comment by GeorgViehoever** [comment]
Hi Nikolai,
below are the error Messages that I get when I try to compile your module. My repository clone of PixInsight/PCL is synced to the latest version.

Kind regards,
Georg
```C++
g++-4.8.2 -c -pipe -m64 -fPIC -D_REENTRANT -D__PCL_LINUX -I"/home/georg/GitHub/PCL/include" -O3 -mtune=generic -mfpmath=sse -msse3 -minline-all-stringops -ffunction-sections -fdata-sections -fomit-frame-pointer -ffast-math -flto -fwhole-program -fvisibility=hidden -fvisibility-inlines-hidden -fnon-call-exceptions -Wall -Wno-parentheses -MMD -MP -MF"x64/Release/CometAlignmentInstance.d" -o"x64/Release/CometAlignmentInstance.o" "../../CometAlignmentInstance.cpp"
In file included from ../../CometAlignmentInstance.cpp:62:0:
/home/georg/GitHub/PCL/include/pcl/DrizzleDataDecoder.h: In Elementfunktion »virtual void pcl::DrizzleSADataDecoder::Validate()«:
/home/georg/GitHub/PCL/include/pcl/DrizzleDataDecoder.h:502:19: Fehler: »pcl::String pcl::DrizzleDataDecoder::m_filePath« ist privat
    String         m_filePath;
                   ^
../../CometAlignmentInstance.cpp:775:8: Fehler: in diesem Zusammenhang
   if ( m_filePath.IsEmpty() )
        ^
In file included from ../../CometAlignmentInstance.cpp:62:0:
/home/georg/GitHub/PCL/include/pcl/DrizzleDataDecoder.h:504:19: Fehler: »int pcl::DrizzleDataDecoder::m_referenceWidth« ist privat
    int            m_referenceWidth;
                   ^
../../CometAlignmentInstance.cpp:777:12: Fehler: in diesem Zusammenhang
       if ( m_referenceWidth < 1 )
            ^
In file included from ../../CometAlignmentInstance.cpp:62:0:
/home/georg/GitHub/PCL/include/pcl/DrizzleDataDecoder.h:505:19: Fehler: »int pcl::DrizzleDataDecoder::m_referenceHeight« ist privat
    int            m_referenceHeight;
                   ^
../../CometAlignmentInstance.cpp:779:12: Fehler: in diesem Zusammenhang
       if ( m_referenceHeight < 1 )
            ^
In file included from ../../CometAlignmentInstance.cpp:62:0:
/home/georg/GitHub/PCL/include/pcl/DrizzleDataDecoder.h:506:19: Fehler: »pcl::Matrix pcl::DrizzleDataDecoder::m_H« ist privat
    Matrix         m_H;
                   ^
../../CometAlignmentInstance.cpp:781:12: Fehler: in diesem Zusammenhang
       if ( m_H.IsEmpty() )
            ^
```

**Comment by nik-volkov** [comment]
Oh, Juan promised to update new DrizzleDataDecoder.h
So I made changes in Line493 of DrizzleDataDecoder and made new Pull Request.

**Comment by jconejero** [comment]
Sorry for the delay, guys. I am having a hard time working on a new Qt5-based version of PixInsight (if you don't know why this is an absolute priority, take a look at the bug reports board on PI Forum - Qt4 simply does not work on OS X Yosemite with the latest updates). I am working like crazy to get a first Qt5-based version ready during this month, at least a temporary version to fix the worst problems while I implement all the new features.

I'm going to merge this request right now, and will release a new version of CA later today. Thank you so much for your great work, Nikolay. AFAIK, this is the first comet alignment tool with drizzle support in the world! ;)

**Pull request merged**
